<?php namespace JF;
/**

Copyright 2016 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-7a00b6
Date:    2016-12-05 03:28:23
Version: v1.0-rc25
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-7a00b6",
    "email": {
        "to": "",
        "cc": "",
        "bcc": "",
        "subject": "",
        "template": ""
    },
    "admin": {
        "users": "admin:a763e",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [
        {
            "disabled": false,
            "action": "show",
            "selector": "c154,c283,c276",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "driversLicense"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "c159,c253,c264",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "stateID"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "c332,c247,c271",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "vehicleReg"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "c252,c244",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "transcripts"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "c138,c291",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "votersReg"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "c138,c291",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "votersReg"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "c154,c283,c276",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "driversLicense"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "c159,c253,c264",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "stateID"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "c332,c247,c271",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "vehicleReg"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "c252,c244",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "transcripts"
                }
            ]
        },
        {
            "disabled": false,
            "action": "disable",
            "selector": "c138,c291",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "votersReg"
                }
            ]
        },
        {
            "disabled": false,
            "action": "disable",
            "selector": "c154,c283,c276",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "driversLicense"
                }
            ]
        },
        {
            "disabled": false,
            "action": "disable",
            "selector": "c159,c253,c264",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "stateID"
                }
            ]
        },
        {
            "disabled": false,
            "action": "disable",
            "selector": "c332,c247,c271",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "vehicleReg"
                }
            ]
        },
        {
            "disabled": false,
            "action": "disable",
            "selector": "c252,c244",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "not contains",
                    "value": "transcripts"
                }
            ]
        },
        {
            "disabled": false,
            "action": "enable",
            "selector": "c138,c291",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "votersReg"
                }
            ]
        },
        {
            "disabled": false,
            "action": "enable",
            "selector": "c154,c283,c276",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "driversLicense"
                }
            ]
        },
        {
            "disabled": false,
            "action": "enable",
            "selector": "c159,c253,c264",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "stateID"
                }
            ]
        },
        {
            "disabled": false,
            "action": "enable",
            "selector": "c332,c247,c271",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "vehicleReg"
                }
            ]
        },
        {
            "disabled": false,
            "action": "enable",
            "selector": "c252,c244",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c127",
                    "condition": "contains",
                    "value": "transcripts"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "c143,c148",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c119",
                    "condition": "!=",
                    "value": "Qualification"
                }
            ]
        },
        {
            "disabled": false,
            "action": "disable",
            "selector": "c143,c148",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c119",
                    "condition": "!=",
                    "value": "Qualification"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "c143,c148",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c119",
                    "condition": "==",
                    "value": "Qualification"
                }
            ]
        },
        {
            "disabled": false,
            "action": "enable",
            "selector": "c143,c148",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "c119",
                    "condition": "==",
                    "value": "Qualification"
                }
            ]
        }
    ],
    "fields": [
        {
            "label": "First Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "firstname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "cid": "c1"
        },
        {
            "label": "Last Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": "lastname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c49"
        },
        {
            "label": "Middle Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": false
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "cid": "c26"
        },
        {
            "label": "Suffix",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Jr",
                        "checked": false
                    },
                    {
                        "label": "Sr",
                        "checked": false
                    },
                    {
                        "label": "I",
                        "checked": false
                    },
                    {
                        "label": "II",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "III",
                        "value": null,
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c83"
        },
        {
            "label": "Term of Application",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Spring",
                        "checked": false
                    },
                    {
                        "label": "Summer",
                        "checked": false
                    },
                    {
                        "label": "Fall",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c90"
        },
        {
            "label": "Year",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "initval": "2017",
                    "step": "1"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c97"
        },
        {
            "label": "Date of Birth",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "date": {
                    "format": "mm\/dd\/yyyy"
                }
            },
            "cid": "c107"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "equalto": {
                        "enabled": false
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                }
            },
            "cid": "c2"
        },
        {
            "label": "TO BE COMPLETED BY THE STUDENT SEEKING FLORIDA RESIDENCY FOR TUITION PURPOSES:",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "description": "I qualify as a resident for tuition purposes, as defined by s. 1009.21, Florida Statutes, for the term for which this application is submitted. I understand that it will be necessary for me topresent evidence of residency for tuition purposes, supporting my claim as a Florida resident for tuition purposes. I have read the residency information on qualifying as a dependent or independent student, and declare that (select one of the options below):"
            },
            "cid": "c124"
        },
        {
            "label": "Student Dependency Status",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "I am a dependent student, as defined by s. 1009.21(1)(a), Florida Statutes, in that I am eligible to be claimed as a dependent under the federal income tax code by the claimant below. The claimant is my \"parent\" as defined by s. 1009.21(1)(f), Florida Statutes, (i.e., either or both parents of the student, any guardian of a student, or any person in a parental relationship to the student). My parent has maintained legal residence in Florida for at least the past 12 consecutive months. As defined by section 1009.21(1)(d), Florida Statutes, \"'legal resident' or 'resident' means a person who has maintained his or her residence in this state for the preceding year, has purchased a home which is occupied by him or her as his or her residence, or has established a domicile in this state pursuant to s. 222.17.\" A copy of your parent's tax return may be requested to establish dependence.",
                        "checked": false,
                        "value": "Dependent"
                    },
                    {
                        "label": "I am an independent person who has maintained legal residence in Florida for at least the past 12 consecutive months. I provide more than 50% of my own support. An independent student generally includes a person who is at least 24 years old, married, a graduate or professional student, a veteran, a member of the armed forces, a ward of the court, or someone with legal dependents other than a spouse, pursuant to the United States Department of Education for the purposes of federal financial aid eligibility. There may be limited cases where a person under the age of 24 years old may qualify as an independent student. Such students will be required to verify independence (including financial independence.) A copy of your tax return may be requested to establish independence.",
                        "checked": false,
                        "value": "Independent"
                    },
                    {
                        "label": "I meet residency requirements through one of the Qualifications by Exception below (check appropriate exception):",
                        "checked": false,
                        "value": "Qualification"
                    }
                ],
                "presetJson": "",
                "description": "",
                "style": {
                    "columns": "col-1"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c119"
        },
        {
            "label": "Qualification by Exception",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "description": "(to be completed by student.) As provided in s. 1009.21, Florida Statutes, I qualify for residency based on the following permitted exception (documentation required):"
            },
            "cid": "c143"
        },
        {
            "label": "",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "I am a qualified beneficiary under the terms of the Florida Prepaid College Program (s. 1009.98, Florida Statutes.) (Required: Copy of Florida Prepaid Recipient card.)",
                        "checked": false,
                        "value": "FlPre"
                    },
                    {
                        "label": "I am married to a person who has maintained legal residence in Florida for at least the past 12 consecutive months. I now have established legal residence and intend to make Florida my permanent home. (Required: copy of marriage certificate and\/or other documents required to establish residency.)",
                        "checked": false,
                        "value": "Marriage"
                    },
                    {
                        "label": "I was previously enrolled at a Florida state postsecondary institution and classified as a Florida resident for tuition purposes. I am transferring to another Florida state postsecondary institution within 12 months of the previous enrollment. (Required: Evidence of previous enrollment as a FL resident)",
                        "checked": false,
                        "value": "Enrollment"
                    },
                    {
                        "label": "I was previously enrolled at a Florida state postsecondary institution and classified as a Florida resident for tuition purposes. I abandoned my Florida domicile less than 12 months ago and am now re-establishing Florida legal residence.",
                        "checked": null,
                        "value": ""
                    },
                    {
                        "label": "Active duty members of the Armed Services of the United States residing in this state and their spouses and dependent children, and active drilling members of the Florida National Guard. (Required: Copy of military orders or DD2058 showing home of record.)",
                        "checked": null
                    },
                    {
                        "label": "Active duty members of the Armed Services of the United States and their spouses and dependents attending a Florida College System institution or state university within 50 miles of the military establishment where they are stationed, if such military establishment is within a county contiguous to Florida. (Required: Copy of military orders.)",
                        "checked": null
                    },
                    {
                        "label": "United States citizens living on the Isthmus of Panama, who have completed 12 consecutive months of college work at the Florida State University Panama Canal Branch, and their spouses and dependent children. (Required: Copy of marriage certificate or proof of dependency.)",
                        "checked": null
                    },
                    {
                        "label": "Full-time instructional and administrative personnel employed by state public schools and institutions of higher education and their spouses and dependent children. (Required: Employment Verification)",
                        "checked": null
                    },
                    {
                        "label": "Students from Latin America and the Caribbean who receive scholarships from the federal or state government. Any student classified pursuant to this paragraph shall attend, on a full-time basis, a Florida institution of higher education. (Required: proof of scholarship and Latin America or Caribbean residency.)",
                        "checked": null
                    },
                    {
                        "label": "Southern Regional Education Board's Academic Common Market graduate students attending Florida's state universities. (Required: Certification letter from State Academic Common Market Coordinator.)",
                        "checked": null
                    },
                    {
                        "label": "Full-time employees of state agencies or political subdivisions of the state when the student fees are paid by the state agency or political subdivision for the purpose of job-related law enforcement or corrections training. (Required: Employment verification\/payment agreement).",
                        "checked": null
                    },
                    {
                        "label": "McKnight Doctoral Fellows and Finalists who are United States citizens. (Required: Verification from graduate studies.)",
                        "checked": null
                    },
                    {
                        "label": "United States citizens living outside the United States who are teaching at a Department of Defense Dependent School or in an American International School and who enroll in a graduate level education program which leads to a Florida teaching certificate. (Required: Proof of enrollment in graduate program for FL teaching certificate.)",
                        "checked": null
                    },
                    {
                        "label": "Active duty members of the Canadian military residing or stationed in this state under the North American Air Defense (NORAD) agreement, and their spouses and dependent children, attending a Florida College System institution or state university within 50 miles of the military establishment where they are stationed. (Required: Proof of active duty membership for specified purpose.)",
                        "checked": null
                    },
                    {
                        "label": "Active duty members of a foreign nation's military who are serving as liasion offciers and are residing or stationed in this state, and their spouses and dependent children, attending a Florida College System institution or state university within 50 miles of the military establishment where the foreign liaison officer is stationed. (Required: Proof of active duty membership for specified purpose.)",
                        "checked": null
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c148"
        },
        {
            "label": "Upload Supporting Documentation",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c120"
        },
        {
            "label": "Claimant Information",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "description": "<strong>TO BE COMPLETED BY THE CLAIMANT \/ PERSON CLAIMING FLORIDA RESIDENCY<\/strong>\nNote: If the student is a dependent, the parent is the claimant and will complete this section and provide evidence of residency supporting the claim. If the student is independent, the student is the claimant and will complete this section and provide evidence of residency supporting the claim. <\/br><b>No single document shall be conclusive in establishing residency. Additional documentation, other than what is prescribed, may be requested in some cases. All documentation provided is subject to verification. Evidence of ties to another state may result in denial of Florida residency for tuition purposes.<\/b>"
            },
            "cid": "c166"
        },
        {
            "label": "Claimant\/Name of Person claiming FL Residency:",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": "fullname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c171"
        },
        {
            "label": "Claimant Relationship to Student:",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c178"
        },
        {
            "label": "Claimant's Address:",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "1234 Yellow Brick Rd."
            },
            "cid": "c192"
        },
        {
            "label": "Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": false,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "cid": "c197"
        },
        {
            "label": "Date Claimant began establishing legal Florida residence:",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "description": "(if upon birth enter birthdate)"
            },
            "cid": "c202"
        },
        {
            "label": "<b>PROVISION OF DOCUMENTS TO SUPPORT CLAIM OF FLORIDA RESIDENCY<\/b>",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "description": "<strong>Per s. 1009.21(3)(c), Florida Statutes, the residency determination must be documented by the submission of written or electronic verification that includes two or more of the documents identified below. No single piece of evidence shall be conclusive.<\/strong>"
            },
            "cid": "c132"
        },
        {
            "label": "<strong>A. Claimant must provide at least one of the following of his\/her personal documentation:<\/strong>",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Florida Voter's registration card",
                        "checked": false,
                        "value": "votersReg"
                    },
                    {
                        "label": "Florida Driver's license",
                        "checked": false,
                        "value": "driversLicense"
                    },
                    {
                        "label": "Florida State ID",
                        "checked": false,
                        "value": "stateID"
                    },
                    {
                        "label": "Florida Vehicle registration",
                        "checked": false,
                        "value": "vehicleReg"
                    },
                    {
                        "label": "Proof of permanent home in Florida occupied as primary residence for 12 consecutive months prior to the student\u2019s enrollment. (Required: document such as a deed or other evidence of title to property used as primary residence, a homeowner\u2019s policy, a title insurance policy, evidence of a property tax payment on the primary residence, multiple leases reflecting a Florida address, or a lease of multiple years\u2019 duration.)",
                        "checked": null,
                        "value": "permHome"
                    },
                    {
                        "label": "Proof of a homestead exemption in Florida. (Required: document from the county tax collector demonstrating the application of a homestead exemption to the claimant\u2019s primary residence.)",
                        "checked": null,
                        "value": "homestead"
                    },
                    {
                        "label": "Official transcripts from a Florida high school for multiple years (2 or more years), if the Florida high school diploma or GED was earned within the last 12 months.",
                        "checked": null,
                        "value": "transcripts"
                    },
                    {
                        "label": "Proof of permanent full-time employment in Florida for at least 30 hours per week for a 12-month period. (Required: pay stubs or W-2 form for past 12 consecutive months and\/or verification from employers, and\/or an IRS 1099 with verification of employment for the past 12 consecutive months from an employer.)",
                        "checked": null,
                        "value": "employment"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": ""
            },
            "cid": "c127"
        },
        {
            "label": "Voter Registration Number",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c138"
        },
        {
            "label": "Issue Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c291"
        },
        {
            "label": "Driver's License Number",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c154"
        },
        {
            "label": "Original Issue Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c283"
        },
        {
            "label": "Current Issue Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c276"
        },
        {
            "label": "Florida State ID Number",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c159"
        },
        {
            "label": "Original Issue Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c253"
        },
        {
            "label": "Current Issue Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c264"
        },
        {
            "label": "Florida Vehicle registration Number",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c332"
        },
        {
            "label": "Original Issue Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c247"
        },
        {
            "label": "Current Issue Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c271"
        },
        {
            "label": "Dates of Attendance",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": false
                    }
                },
                "hidden": true
            },
            "cid": "c252"
        },
        {
            "label": "Graduation Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "cid": "c244"
        },
        {
            "label": "<strong>B. Claimant may provide one or more documents from the following categories to demonstrate residency in Florida (to be used in conjunction with one document from above):<\/strong>",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Declaration of domicile in Florida in accordance with s. 222.17, Florida Statutes.",
                        "checked": false,
                        "value": "domicile"
                    },
                    {
                        "label": "Florida professional or occupational license.",
                        "checked": false,
                        "value": "profLicense"
                    },
                    {
                        "label": "Florida incorporation.",
                        "checked": false,
                        "value": "incorporation"
                    },
                    {
                        "label": "Document evidencing family ties in Florida",
                        "checked": null,
                        "value": "family"
                    },
                    {
                        "label": "Proof of membership in a Florida-based charitable or professional organization.",
                        "checked": null,
                        "value": "membership"
                    },
                    {
                        "label": "Any other documentation that supports your request for resident status, including, but not limited to, utility bills and proof of 12 consecutive months of payments; a lease agreement and proof of 12 consecutive months of payments; or an official state, federal, or court document evidencing legal ties to Florida.",
                        "checked": null,
                        "value": "other"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": ""
            },
            "cid": "c144"
        },
        {
            "label": "Residency Declaration",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "description": "<strong>I, the undersigned, hereby declare that I have read the foregoing document and that the facts stated in it are true and further affirm the authenticity of the information provided on all pages of this Residency Declaration. I understand that any false or misleading information on this Residency Declaration, or provided in support of this Residency Declaration, will subject me to penalties pursuant to section 837.06, Florida Statutes, for making a false statement. I give permission for the institution to review or examine any and all documents and records, including those accessible electronically, which may assist in support of my claim as a Florida resident for tuition purposes.<\/strong>"
            },
            "cid": "c207"
        },
        {
            "label": "Student Name:",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": "fullname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c212"
        },
        {
            "label": "Claimant Name (if not the student):",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": "fullname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c217"
        },
        {
            "label": "Signature of claimant:",
            "field_type": "signature",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "signature": {
                "labelClear": "Clear",
                "width": "400",
                "height": "120"
            },
            "cid": "c222"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "cid": "c100"
        }
    ]
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class